music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'
urlpatterns = [
    #/music/
    url(r'^$',views.index, name = 'index'),

    #/music/765/
    url(r'^(?P<album_id>[0-9]+)/$', views.details,name = 'details')

    # #/music/<album_id>/favourite
    # url(r'^(?P<album_id>[0-9]+)/favourite$', views.favourite,name = 'favourite')
]

websitedemo/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include('music.urls'))
]

music/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Albums(models.Model):

    artist = models.CharField(max_length = 250)
    ablum_title = models.CharField(max_length = 500)
    genre = models.CharField(max_length = 100)
    album_logo = models.CharField(max_length = 1000)

    def __str__(self):
        return self.artist + ' - ' + self.ablum_title

class Songs(models.Model):

    album = models.ForeignKey(Albums,on_delete = models.CASCADE)
    file_type = models.CharField(max_length = 50)
    song_title = models.CharField(max_length = 100)
    is_favourite = models.BooleanField(default = False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render,get_object_or_404
#from django.http import HttpResponse
from . models import Albums
#from django.template import loader
from django.http import Http404

# Create your views here.
def index(request):
    all_albums = Albums.objects.all()
    #template = loader.get_template("music/index.html")
    context = {"all_albums" : all_albums}
    #return HttpResponse(template.render(context,request))
    return render(request,"music/index.html",context)
    

def details(request,album_id):
    
    # try:
    #     album = Albums.objects.get(pk = album_id)
    # except:
    #     raise Http404("Album does not exist")

    album = get_object_or_404(Albums,pk = album_id)
    return render(request,"music/details.html",{"album" : album})

music/templates/music/details.html
<h2>Album Details</h2>
<img src = "{{album.album_logo}}">

<h1>{{album.ablum_title}}</h1>
<h3>Artist : {{album.artist}}</h3>

<ul>
    {%for album in album.songs_set.all%}
        <li>{{album.song_title}} - {{album.file_type}}</li>
    {%endfor%}
</ul>

music/templates/music/index.html
<h2>List of all albums</h2>
{%if all_albums%}
    <ul>
        {%for album in all_albums%}
          <!--<li><a href = "/music/{{album.id}}/">{{album.ablum_title}}</a></li>-->
       
        
        <li><a href = "{% url 'music:details' album.id%}">{{album.ablum_title}}</a></li>
        {%endfor%}
    </ul>
{%else%}
    <h3>You don't have any albums</h3>
{%endif%}